version: "3.8"

services:
  app:
    container_name: rust-on-docker
    build:
      context: .
      dockerfile: Dockerfile
    image: rust-on-docker
    volumes:
      - .:/app
    ports:
      - 8080:8080
